#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="starship,vscode,personal,wireshark,bash,tmux,taskwarrior,bin,nvim,fonts"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

#Check if we are using the default .zshrc file
if [ -f "$HOME/.zshrc" ]; then
	echo "Deleting default .zshrc file"
	rm $HOME/.zshrc
fi

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow --restow $folder
done
popd
