#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="starship,vscode,personal,wireshark,bash,tmux,bin"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

#Check if we are using the default .zshrc file
if [ -f "$HOME/.zshrc" ]; then
	echo "Deleting default .zshrc file"
	rm $HOME/.zshrc
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install

